/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface RaiseDark {
    }
    interface RaiseForm {
    }
    interface RaiseIbatitude {
    }
    interface RaiseLight {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLRaiseDarkElement extends Components.RaiseDark, HTMLStencilElement {
    }
    var HTMLRaiseDarkElement: {
        prototype: HTMLRaiseDarkElement;
        new (): HTMLRaiseDarkElement;
    };
    interface HTMLRaiseFormElement extends Components.RaiseForm, HTMLStencilElement {
    }
    var HTMLRaiseFormElement: {
        prototype: HTMLRaiseFormElement;
        new (): HTMLRaiseFormElement;
    };
    interface HTMLRaiseIbatitudeElement extends Components.RaiseIbatitude, HTMLStencilElement {
    }
    var HTMLRaiseIbatitudeElement: {
        prototype: HTMLRaiseIbatitudeElement;
        new (): HTMLRaiseIbatitudeElement;
    };
    interface HTMLRaiseLightElement extends Components.RaiseLight, HTMLStencilElement {
    }
    var HTMLRaiseLightElement: {
        prototype: HTMLRaiseLightElement;
        new (): HTMLRaiseLightElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "raise-dark": HTMLRaiseDarkElement;
        "raise-form": HTMLRaiseFormElement;
        "raise-ibatitude": HTMLRaiseIbatitudeElement;
        "raise-light": HTMLRaiseLightElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface RaiseDark {
    }
    interface RaiseForm {
    }
    interface RaiseIbatitude {
    }
    interface RaiseLight {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "raise-dark": RaiseDark;
        "raise-form": RaiseForm;
        "raise-ibatitude": RaiseIbatitude;
        "raise-light": RaiseLight;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "raise-dark": LocalJSX.RaiseDark & JSXBase.HTMLAttributes<HTMLRaiseDarkElement>;
            "raise-form": LocalJSX.RaiseForm & JSXBase.HTMLAttributes<HTMLRaiseFormElement>;
            "raise-ibatitude": LocalJSX.RaiseIbatitude & JSXBase.HTMLAttributes<HTMLRaiseIbatitudeElement>;
            "raise-light": LocalJSX.RaiseLight & JSXBase.HTMLAttributes<HTMLRaiseLightElement>;
        }
    }
}
